// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: Comprobante_de_Retención_V1.0.0.xsd
// Creation Date: 8/8/2016 9:46:08 AM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.ComponentModel;
using general.xml;

/// <summary>
/// Entidad de comprobante de retención
/// </summary>

namespace facturacionelectronica.comp.consulta.esquemasri.documentos.comprobanteRetencion
{

    public struct Declarations
    {
        public const string SchemaVersion = "";
    }

    [Serializable]
    public enum id
    {
        [XmlEnum(Name = "comprobante")] comprobante
    }

    [Serializable]
    public enum obligadoContabilidad
    {
        [XmlEnum(Name = "SI")] SI,
        [XmlEnum(Name = "NO")] NO
    }


    [Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class campoAdicionalCollection : ArrayList
    {
        public campoAdicional Add(campoAdicional obj)
        {
            base.Add(obj);
            return obj;
        }

        public campoAdicional Add()
        {
            return Add(new campoAdicional());
        }

        public void Insert(int index, campoAdicional obj)
        {
            base.Insert(index, obj);
        }

        public void Remove(campoAdicional obj)
        {
            base.Remove(obj);
        }

        new public campoAdicional this[int index]
        {
            get { return (campoAdicional)base[index]; }
            set { base[index] = value; }
        }
    }

    [Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class impuestoCollection : ArrayList
    {
        public impuesto Add(impuesto obj)
        {
            base.Add(obj);
            return obj;
        }

        public impuesto Add()
        {
            return Add(new impuesto());
        }

        public void Insert(int index, impuesto obj)
        {
            base.Insert(index, obj);
        }

        public void Remove(impuesto obj)
        {
            base.Remove(obj);
        }

        new public impuesto this[int index]
        {
            get { return (impuesto)base[index]; }
            set { base[index] = value; }
        }
    }



    [XmlType(TypeName = "impuesto"), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class impuesto
    {

        [XmlElement(ElementName = "codigo", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __codigo;

        [XmlIgnore]
        public string codigo
        {
            get { return __codigo; }
            set { __codigo = value; }
        }

        [XmlElement(ElementName = "codigoRetencion", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __codigoRetencion;

        [XmlIgnore]
        public string codigoRetencion
        {
            get { return __codigoRetencion; }
            set { __codigoRetencion = value; }
        }

        [XmlElement(ElementName = "baseImponible", IsNullable = false, DataType = "decimal")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public decimal __baseImponible;

        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __baseImponibleSpecified;

        [XmlIgnore]
        public decimal baseImponible
        {
            get { return __baseImponible; }
            set { __baseImponible = value; __baseImponibleSpecified = true; }
        }

        [XmlElement(ElementName = "porcentajeRetener", IsNullable = false, DataType = "decimal")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public decimal __porcentajeRetener;

        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __porcentajeRetenerSpecified;

        [XmlIgnore]
        public decimal porcentajeRetener
        {
            get { return __porcentajeRetener; }
            set { __porcentajeRetener = value; __porcentajeRetenerSpecified = true; }
        }

        [XmlElement(ElementName = "valorRetenido", IsNullable = false, DataType = "decimal")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public decimal __valorRetenido;

        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __valorRetenidoSpecified;

        [XmlIgnore]
        public decimal valorRetenido
        {
            get { return __valorRetenido; }
            set { __valorRetenido = value; __valorRetenidoSpecified = true; }
        }

        [XmlElement(ElementName = "codDocSustento", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __codDocSustento;

        [XmlIgnore]
        public string codDocSustento
        {
            get { return __codDocSustento; }
            set { __codDocSustento = value; }
        }

        [XmlElement(ElementName = "numDocSustento", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __numDocSustento;

        [XmlIgnore]
        public string numDocSustento
        {
            get { return __numDocSustento; }
            set { __numDocSustento = value; }
        }

        [XmlElement(ElementName = "fechaEmisionDocSustento", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __fechaEmisionDocSustento;

        [XmlIgnore]
        public string fechaEmisionDocSustento
        {
            get { return __fechaEmisionDocSustento; }
            set { __fechaEmisionDocSustento = value; }
        }

        public impuesto()
        {
        }
    }


    [XmlType(TypeName = "infoTributaria"), Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class infoTributaria
    {

        [XmlElement(ElementName = "ambiente", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __ambiente;

        [XmlIgnore]
        public string ambiente
        {
            get { return __ambiente; }
            set { __ambiente = value; }
        }

        [XmlElement(ElementName = "tipoEmision", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __tipoEmision;

        [XmlIgnore]
        public string tipoEmision
        {
            get { return __tipoEmision; }
            set { __tipoEmision = value; }
        }

        [XmlElement(ElementName = "razonSocial", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __razonSocial;

        [XmlIgnore]
        public string razonSocial
        {
            get { return __razonSocial; }
            set { __razonSocial = value; }
        }

        [XmlElement(ElementName = "nombreComercial", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __nombreComercial;

        [XmlIgnore]
        public string nombreComercial
        {
            get { return __nombreComercial; }
            set { __nombreComercial = value; }
        }

        [XmlElement(ElementName = "ruc", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __ruc;

        [XmlIgnore]
        public string ruc
        {
            get { return __ruc; }
            set { __ruc = value; }
        }

        [XmlElement(ElementName = "claveAcceso", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __claveAcceso;

        [XmlIgnore]
        public string claveAcceso
        {
            get { return __claveAcceso; }
            set { __claveAcceso = value; }
        }

        [XmlElement(ElementName = "codDoc", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __codDoc;

        [XmlIgnore]
        public string codDoc
        {
            get { return __codDoc; }
            set { __codDoc = value; }
        }

        [XmlElement(ElementName = "estab", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __estab;

        [XmlIgnore]
        public string estab
        {
            get { return __estab; }
            set { __estab = value; }
        }

        [XmlElement(ElementName = "ptoEmi", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __ptoEmi;

        [XmlIgnore]
        public string ptoEmi
        {
            get { return __ptoEmi; }
            set { __ptoEmi = value; }
        }

        [XmlElement(ElementName = "secuencial", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __secuencial;

        [XmlIgnore]
        public string secuencial
        {
            get { return __secuencial; }
            set { __secuencial = value; }
        }

        [XmlElement(ElementName = "dirMatriz", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __dirMatriz;

        [XmlIgnore]
        public string dirMatriz
        {
            get { return __dirMatriz; }
            set { __dirMatriz = value; }
        }

        public infoTributaria()
        {
        }
    }


    [XmlRoot(ElementName = "comprobanteRetencion", IsNullable = false), Serializable]
    public class comprobanteRetencion : BusinessEntity
    {

        [XmlAttribute(AttributeName = "id")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public id __id;

        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __idSpecified;

        [XmlIgnore]
        public id id
        {
            get { return __id; }
            set { __id = value; __idSpecified = true; }
        }

        [XmlAttribute(AttributeName = "version", DataType = "NMTOKEN")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __version;

        [XmlIgnore]
        public string version
        {
            get { return __version; }
            set { __version = value; }
        }

        [XmlElement(Type = typeof(infoTributaria), ElementName = "infoTributaria", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public infoTributaria __infoTributaria;

        [XmlIgnore]
        public infoTributaria infoTributaria
        {
            get
            {
                if (__infoTributaria == null) __infoTributaria = new infoTributaria();
                return __infoTributaria;
            }
            set { __infoTributaria = value; }
        }

        [XmlElement(Type = typeof(infoCompRetencion), ElementName = "infoCompRetencion", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public infoCompRetencion __infoCompRetencion;

        [XmlIgnore]
        public infoCompRetencion infoCompRetencion
        {
            get
            {
                if (__infoCompRetencion == null) __infoCompRetencion = new infoCompRetencion();
                return __infoCompRetencion;
            }
            set { __infoCompRetencion = value; }
        }

        [XmlElement(Type = typeof(impuestos), ElementName = "impuestos", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public impuestos __impuestos;

        [XmlIgnore]
        public impuestos impuestos
        {
            get
            {
                if (__impuestos == null) __impuestos = new impuestos();
                return __impuestos;
            }
            set { __impuestos = value; }
        }

        [XmlElement(Type = typeof(infoAdicional), ElementName = "infoAdicional", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public infoAdicional __infoAdicional;

        [XmlIgnore]
        public infoAdicional infoAdicional
        {
            get
            {
                if (__infoAdicional == null) __infoAdicional = new infoAdicional();
                return __infoAdicional;
            }
            set { __infoAdicional = value; }
        }

        public comprobanteRetencion()
        {
        }
    }


    [XmlType(TypeName = "infoCompRetencion"), Serializable]
    public class infoCompRetencion
    {

        [XmlElement(ElementName = "fechaEmision", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __fechaEmision;

        [XmlIgnore]
        public string fechaEmision
        {
            get { return __fechaEmision; }
            set { __fechaEmision = value; }
        }

        [XmlElement(ElementName = "dirEstablecimiento", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __dirEstablecimiento;

        [XmlIgnore]
        public string dirEstablecimiento
        {
            get { return __dirEstablecimiento; }
            set { __dirEstablecimiento = value; }
        }

        [XmlElement(ElementName = "contribuyenteEspecial", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __contribuyenteEspecial;

        [XmlIgnore]
        public string contribuyenteEspecial
        {
            get { return __contribuyenteEspecial; }
            set { __contribuyenteEspecial = value; }
        }

        [XmlElement(ElementName = "obligadoContabilidad", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public obligadoContabilidad __obligadoContabilidad;

        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __obligadoContabilidadSpecified;

        [XmlIgnore]
        public obligadoContabilidad obligadoContabilidad
        {
            get { return __obligadoContabilidad; }
            set { __obligadoContabilidad = value; __obligadoContabilidadSpecified = true; }
        }

        [XmlElement(ElementName = "tipoIdentificacionSujetoRetenido", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __tipoIdentificacionSujetoRetenido;

        [XmlIgnore]
        public string tipoIdentificacionSujetoRetenido
        {
            get { return __tipoIdentificacionSujetoRetenido; }
            set { __tipoIdentificacionSujetoRetenido = value; }
        }

        [XmlElement(ElementName = "razonSocialSujetoRetenido", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __razonSocialSujetoRetenido;

        [XmlIgnore]
        public string razonSocialSujetoRetenido
        {
            get { return __razonSocialSujetoRetenido; }
            set { __razonSocialSujetoRetenido = value; }
        }

        [XmlElement(ElementName = "identificacionSujetoRetenido", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __identificacionSujetoRetenido;

        [XmlIgnore]
        public string identificacionSujetoRetenido
        {
            get { return __identificacionSujetoRetenido; }
            set { __identificacionSujetoRetenido = value; }
        }

        [XmlElement(ElementName = "periodoFiscal", IsNullable = false, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __periodoFiscal;

        [XmlIgnore]
        public string periodoFiscal
        {
            get { return __periodoFiscal; }
            set { __periodoFiscal = value; }
        }

        public infoCompRetencion()
        {
        }
    }


    [XmlType(TypeName = "impuestos"), Serializable]
    public class impuestos
    {
        [System.Runtime.InteropServices.DispIdAttribute(-4)]
        public IEnumerator GetEnumerator()
        {
            return impuestoCollection.GetEnumerator();
        }

        public impuesto Add(impuesto obj)
        {
            return impuestoCollection.Add(obj);
        }

        [XmlIgnore]
        public impuesto this[int index]
        {
            get { return (impuesto)impuestoCollection[index]; }
        }

        [XmlIgnore]
        public int Count
        {
            get { return impuestoCollection.Count; }
        }

        public void Clear()
        {
            impuestoCollection.Clear();
        }

        public impuesto Remove(int index)
        {
            impuesto obj = impuestoCollection[index];
            impuestoCollection.Remove(obj);
            return obj;
        }

        public void Remove(object obj)
        {
            impuestoCollection.Remove(obj);
        }

        [XmlElement(Type = typeof(impuesto), ElementName = "impuesto", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public impuestoCollection __impuestoCollection;

        [XmlIgnore]
        public impuestoCollection impuestoCollection
        {
            get
            {
                if (__impuestoCollection == null) __impuestoCollection = new impuestoCollection();
                return __impuestoCollection;
            }
            set { __impuestoCollection = value; }
        }

        public impuestos()
        {
        }
    }


    [XmlType(TypeName = "infoAdicional"), Serializable]
    public class infoAdicional
    {
        [System.Runtime.InteropServices.DispIdAttribute(-4)]
        public IEnumerator GetEnumerator()
        {
            return campoAdicionalCollection.GetEnumerator();
        }

        public campoAdicional Add(campoAdicional obj)
        {
            return campoAdicionalCollection.Add(obj);
        }

        [XmlIgnore]
        public campoAdicional this[int index]
        {
            get { return (campoAdicional)campoAdicionalCollection[index]; }
        }

        [XmlIgnore]
        public int Count
        {
            get { return campoAdicionalCollection.Count; }
        }

        public void Clear()
        {
            campoAdicionalCollection.Clear();
        }

        public campoAdicional Remove(int index)
        {
            campoAdicional obj = campoAdicionalCollection[index];
            campoAdicionalCollection.Remove(obj);
            return obj;
        }

        public void Remove(object obj)
        {
            campoAdicionalCollection.Remove(obj);
        }

        [XmlElement(Type = typeof(campoAdicional), ElementName = "campoAdicional", IsNullable = false)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public campoAdicionalCollection __campoAdicionalCollection;

        [XmlIgnore]
        public campoAdicionalCollection campoAdicionalCollection
        {
            get
            {
                if (__campoAdicionalCollection == null) __campoAdicionalCollection = new campoAdicionalCollection();
                return __campoAdicionalCollection;
            }
            set { __campoAdicionalCollection = value; }
        }

        public infoAdicional()
        {
        }
    }


    [XmlType(TypeName = "campoAdicional"), Serializable]
    public class campoAdicional
    {

        [XmlAttribute(AttributeName = "nombre", DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __nombre;

        [XmlIgnore]
        public string nombre
        {
            get { return __nombre; }
            set { __nombre = value; }
        }

        [XmlText(DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __Value;

        [XmlIgnore]
        public string Value
        {
            get { return __Value; }
            set { __Value = value; }
        }

        public campoAdicional()
        {
        }
    }
}
