//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tacfproducto: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tacfproducto()
        {
        }
    
        public int cproducto { get; set; }
        public Nullable<int> padre { get; set; }
        public Nullable<int> ctipoproducto { get; set; }
        public Nullable<int> cunidad { get; set; }
        public Nullable<int> ccompania { get; set; }
        public string ccuenta { get; set; }
        public string ccuentadepreciacion { get; set; }
        public string ccuentagasto { get; set; }
        public string ccuentadepreciacionacum { get; set; }
        public string codigo { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<int> verreg { get; set; }
        public Nullable<bool> movimiento { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> cantidadtotal { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<decimal> stockminimo { get; set; }
        public Nullable<decimal> vunitario { get; set; }
        public Nullable<decimal> valorlibros { get; set; }
        public Nullable<bool> depreciable { get; set; }
        public Nullable<decimal> porcendepreciacion { get; set; }
        public Nullable<int> vidautil { get; set; }
        public Nullable<decimal> valorresidual { get; set; }
        public Nullable<System.DateTime> fultcompra { get; set; }
        public Nullable<bool> gravaiva { get; set; }
        public Nullable<bool> codificable { get; set; }
        public Nullable<bool> catalogado { get; set; }
        public string cuentahomologada1 { get; set; }
        public string cuentahomologada2 { get; set; }
        public Nullable<int> estadoccatalogo { get; set; }
        public string estadocdetalle { get; set; }
        public Nullable<int> marcaccatalogo { get; set; }
        public string marcacdetalle { get; set; }
        public Nullable<int> centrocostosccatalogo { get; set; }
        public string centrocostoscdetalle { get; set; }
        public string modelo { get; set; }
        public string infoadicional { get; set; }
        public string comentario { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public Nullable<bool> grcodificable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfajustedetalle> tacfajustedetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfegresodetalle> tacfegresodetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfhistorialdepreciacion> tacfhistorialdepreciacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfhistorialrevalorizacion> tacfhistorialrevalorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfingresodetalle> tacfingresodetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfkardexprodcodi> tacfkardexprodcodi { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle1 { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfproductocodificado> tacfproductocodificado { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tacftipoproducto tacftipoproducto { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tacfunidad tacfunidad { get; set; }
    }
}
