//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tacfingresodetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int cproducto { get; set; }
        public int cingreso { get; set; }
        public int secuencia { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> cantidaddevuelta { get; set; }
        public Nullable<decimal> vunitario { get; set; }
        public Nullable<int> porcentajeiva { get; set; }
        public Nullable<decimal> valoriva { get; set; }
        public Nullable<decimal> stock { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tacfingreso tacfingreso { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tacfproducto tacfproducto { get; set; }
    }
}
