//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tacfajuste: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tacfajuste()
        {
        }
    
        public int cajuste { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<long> optlock { get; set; }
        public string docautorizacion { get; set; }
        public string docrequerimiento { get; set; }
        public bool tienekardex { get; set; }
        public bool eliminado { get; set; }
        public string comentario { get; set; }
        public string cusuarioautoriza { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public Nullable<decimal> total { get; set; }
        public string movimiento { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuarioavala { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfajustedetalle> tacfajustedetalle { get; set; }
    }
}
