//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tacfegreso: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tacfegreso()
        {
        }
    
        public int cegreso { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<int> verreg { get; set; }
        public string ccomprobante { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numeromemo { get; set; }
        public string numerooficio { get; set; }
        public string cusuarioautorizado { get; set; }
        public string cusuariorecibe { get; set; }
        public bool tienekardex { get; set; }
        public string movimiento { get; set; }
        public bool eliminado { get; set; }
        public string comentario { get; set; }
        public Nullable<int> tipoegresoccatalogo { get; set; }
        public string tipoegresocdetalle { get; set; }
        public Nullable<int> estadoccatalogo { get; set; }
        public string estadocdetalle { get; set; }
        public Nullable<long> carea { get; set; }
        public Nullable<long> ccargo { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tacfegresodetalle> tacfegresodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle1 { get; set; }
    }
}
