//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tacfhistorialrevalorizacion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int chrevalorizacion { get; set; }
        public Nullable<int> cproducto { get; set; }
        public string cbarras { get; set; }
        public string ccomprobante { get; set; }
        public Nullable<decimal> valorunitario { get; set; }
        public Nullable<decimal> valorlibros { get; set; }
        public Nullable<decimal> valoravaluo { get; set; }
        public string infoadicional { get; set; }
        public string comentario { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tacfproducto tacfproducto { get; set; }
    }
}
