//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tbanusuariosessionhistoria: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string cusuario { get; set; }
        public System.DateTime fcreacion { get; set; }
        public int ccompania { get; set; }
        public string cterminal { get; set; }
        public Nullable<int> numerointentos { get; set; }
        public string idsession { get; set; }
        public string ipwebserver { get; set; }
        public Nullable<System.DateTime> finicio { get; set; }
        public Nullable<System.DateTime> fsalida { get; set; }
        public string cestado { get; set; }
        public string useragent { get; set; }
        public string cterminalremoto { get; set; }
    }
}
