//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tbansuscripcion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string identificacion { get; set; }
        public string cusuario { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string password { get; set; }
        public string tipopersona { get; set; }
        public string passwordotp { get; set; }
        public Nullable<System.DateTime> fcreacionotp { get; set; }
        public Nullable<System.DateTime> fcaducidadotp { get; set; }
        public Nullable<int> estatuscusuarioccatalogo { get; set; }
        public string estatuscusuariocdetalle { get; set; }
        public string observacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    }
}
