//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcanusuarioclave: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int cclave { get; set; }
        public string cusuario { get; set; }
        public string ccanal { get; set; }
        public string password { get; set; }
        public Nullable<bool> temporal { get; set; }
        public System.DateTime fcreacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tcanusuario tcanusuario { get; set; }
    }
}
