//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcanhorarioatencion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcanhorarioatencion()
        {
        }
    
        public long chorario { get; set; }
        public int cagencia { get; set; }
        public int csucursal { get; set; }
        public int ccompania { get; set; }
        public int fatencion { get; set; }
        public string hinicio { get; set; }
        public string hfin { get; set; }
        public int intervalo { get; set; }
        public int agentes { get; set; }
        public int citasreservadas { get; set; }
        public bool activo { get; set; }
        public string cusuarioing { get; set; }
        public System.DateTime fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public bool descanso { get; set; }
        public string hiniciodescanso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tcanagendamiento> tcanagendamiento { get; set; }
    }
}
