//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcaroperacionrubromora: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string mensaje { get; set; }
        public string coperacion { get; set; }
        public int numcuota { get; set; }
        public Nullable<int> ftrabajo { get; set; }
        public Nullable<int> fvencimientocuota { get; set; }
        public Nullable<int> fpago { get; set; }
        public Nullable<decimal> capitalpagado { get; set; }
        public Nullable<decimal> tasaoperacion { get; set; }
        public Nullable<decimal> tasamora { get; set; }
        public Nullable<decimal> mora { get; set; }
        public Nullable<decimal> moracobrada { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tcaroperacion tcaroperacion { get; set; }
    }
}
