//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcaroperacionarreglopago: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcaroperacionarreglopago()
        {
        }
    
        public string coperacion { get; set; }
        public string ctipoarreglopago { get; set; }
        public long csolicitud { get; set; }
        public string cestatus { get; set; }
        public string cusuarioingreso { get; set; }
        public Nullable<int> fingreso { get; set; }
        public string cusuarioaprueba { get; set; }
        public Nullable<int> faprueba { get; set; }
        public string cusuariocancela { get; set; }
        public Nullable<int> fcancelacion { get; set; }
        public Nullable<int> fpago { get; set; }
        public Nullable<int> numerocuotas { get; set; }
        public Nullable<decimal> valorcuota { get; set; }
        public Nullable<int> finiciopagos { get; set; }
        public Nullable<decimal> montoincremento { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tcaroperacion tcaroperacion { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tcartipoarreglopago tcartipoarreglopago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tcaroperacionarrepagorubro> tcaroperacionarrepagorubro { get; set; }
    }
}
