//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcardescuentos: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int particion { get; set; }
        public int fgeneracion { get; set; }
        public Nullable<bool> pagoaplicado { get; set; }
        public Nullable<int> sumcpersona { get; set; }
        public Nullable<int> sumcoperacion { get; set; }
        public Nullable<decimal> summonto { get; set; }
    }
}
