//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcarmovimiento: Movimiento,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string mensaje { get; set; }
        public int particion { get; set; }
        public int secmensaje { get; set; }
        public Nullable<int> fcontable { get; set; }
        public Nullable<int> ftrabajo { get; set; }
        public Nullable<int> fproceso { get; set; }
        public Nullable<int> fvalor { get; set; }
        public Nullable<System.DateTime> freal { get; set; }
        public Nullable<int> ctransaccion { get; set; }
        public Nullable<int> cmodulotransaccion { get; set; }
        public Nullable<int> crubro { get; set; }
        public string csaldo { get; set; }
        public string cclase { get; set; }
        public Nullable<int> ctransaccionorigen { get; set; }
        public Nullable<int> cmoduloorigen { get; set; }
        public string coperacion { get; set; }
        public string cestatus { get; set; }
        public string cmoneda { get; set; }
        public Nullable<decimal> montomonedalocal { get; set; }
        public string cmonedalocal { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> debito { get; set; }
        public Nullable<int> cmodulo { get; set; }
        public Nullable<int> cproducto { get; set; }
        public Nullable<int> ctipoproducto { get; set; }
        public Nullable<long> cpersona { get; set; }
        public Nullable<int> csucursal { get; set; }
        public Nullable<int> cagencia { get; set; }
        public Nullable<int> ccompania { get; set; }
        public Nullable<int> csucursalorigen { get; set; }
        public Nullable<int> cagenciaorigen { get; set; }
        public string cterminal { get; set; }
        public string cusuario { get; set; }
        public string cusuarioreverso { get; set; }
        public string documento { get; set; }
        public string imperativo { get; set; }
        public string reverso { get; set; }
        public string mensajereverso { get; set; }
        public Nullable<decimal> cotcompra { get; set; }
        public Nullable<decimal> cotventa { get; set; }
        public string tipocredito { get; set; }
        public string ccuenta { get; set; }
        public Nullable<int> numcuota { get; set; }
        public Nullable<bool> actualizasaldo { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcatalogo tconcatalogo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tmonsaldo tmonsaldo { get; set; }
    }
}
