//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcarsaldoscierre: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int fcierre { get; set; }
        public int particion { get; set; }
        public string coperacion { get; set; }
        public string cestatus { get; set; }
        public Nullable<decimal> saldocapital { get; set; }
        public Nullable<decimal> saldointeres { get; set; }
        public Nullable<decimal> saldomora { get; set; }
        public Nullable<decimal> saldoseguro { get; set; }
        public Nullable<decimal> saldocargo { get; set; }
        public Nullable<decimal> saldocxc { get; set; }
        public Nullable<decimal> saldocxp { get; set; }
        public Nullable<decimal> capitalvencido { get; set; }
        public Nullable<decimal> capitalxvencer { get; set; }
        public Nullable<decimal> montovencido { get; set; }
        public Nullable<int> numerocuotasvencidas { get; set; }
        public Nullable<int> diasvencido { get; set; }
    }
}
