//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcarsolicitudtasa: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long csolicitud { get; set; }
        public string csaldo { get; set; }
        public int ctasareferencial { get; set; }
        public string cmoneda { get; set; }
        public decimal tasabase { get; set; }
        public string operador { get; set; }
        public decimal margen { get; set; }
        public decimal tasa { get; set; }
        public decimal tasaefectiva { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgentasareferencial tgentasareferencial { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tmonsaldo tmonsaldo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgensolicitud tgensolicitud { get; set; }
    }
}
