//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcarsolicituddesembolso: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long csolicitud { get; set; }
        public int secuencia { get; set; }
        public Nullable<int> fregistro { get; set; }
        public string tipo { get; set; }
        public Nullable<decimal> valor { get; set; }
        public int crubro { get; set; }
        public string csaldo { get; set; }
        public Nullable<int> tipoidentificacionccatalogo { get; set; }
        public string tipoidentificacioncdetalle { get; set; }
        public string identificacionbeneficiario { get; set; }
        public string nombrebeneficiario { get; set; }
        public Nullable<int> tipoinstitucionccatalogo { get; set; }
        public string tipoinstitucioncdetalle { get; set; }
        public Nullable<int> tipocuentaccatalogo { get; set; }
        public string tipocuentacdetalle { get; set; }
        public string numerocuentabancaria { get; set; }
        public Nullable<bool> cuentacliente { get; set; }
        public Nullable<bool> transferencia { get; set; }
        public Nullable<bool> pagado { get; set; }
        public string comentario { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgensolicitud tgensolicitud { get; set; }
    }
}
