//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcaroperacioncalificahistoria: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string coperacion { get; set; }
        public int fcalificacion { get; set; }
        public string cmoneda { get; set; }
        public string ccalificacion { get; set; }
        public string ccalificacionanterior { get; set; }
        public string ccalificacionlegal { get; set; }
        public string ccalificacionlegalanterior { get; set; }
        public string csegmento { get; set; }
        public string cestadooperacion { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> porcentajeprovconstituida { get; set; }
        public Nullable<decimal> porcentajeprovconstituidaant { get; set; }
        public Nullable<decimal> porcentajeprovisionreq { get; set; }
        public Nullable<decimal> porcentajeprovisionreqant { get; set; }
        public Nullable<decimal> provisionrequerida { get; set; }
        public Nullable<decimal> provisionconstituida { get; set; }
        public Nullable<decimal> provisionrequeridaant { get; set; }
        public Nullable<decimal> provisionconstituidaant { get; set; }
        public Nullable<int> diasmorosidad { get; set; }
        public Nullable<bool> contabilizaprovision { get; set; }
        public Nullable<bool> reversoprovanterior { get; set; }
        public Nullable<decimal> saldo { get; set; }
    }
}
