//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcaroperacionrubro: Rubro,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string coperacion { get; set; }
        public int numcuota { get; set; }
        public string csaldo { get; set; }
        public Nullable<int> fvigencia { get; set; }
        public Nullable<decimal> valorcuota { get; set; }
        public Nullable<decimal> interesdeudor { get; set; }
        public Nullable<bool> esaccrual { get; set; }
        public Nullable<decimal> montoparaaccrual { get; set; }
        public Nullable<decimal> accrual { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> cobrado { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public Nullable<decimal> tasadia { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> accrualotrosanios { get; set; }
        public string codigocontable { get; set; }
        public Nullable<int> fpago { get; set; }
        public string mensaje { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tmonsaldo tmonsaldo { get; set; }
    }
}
