//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tcelsecuenciasri: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string csecuenciasri { get; set; }
        public Nullable<int> tipodocumentoccatalogo { get; set; }
        public string tipodocumentocdetalle { get; set; }
        public string establecimiento { get; set; }
        public string puntodeemision { get; set; }
        public Nullable<long> secuenciaactual { get; set; }
        public Nullable<bool> estado { get; set; }
        public string direccionestablecimiento { get; set; }
    }
}
