//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconcuentaporcobrar: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tconcuentaporcobrar()
        {
        }
    
        public string cctaporcobrar { get; set; }
        public Nullable<int> cplantilla { get; set; }
        public string ccodfactura { get; set; }
        public string oficina { get; set; }
        public string ccompcontable { get; set; }
        public Nullable<long> cpersona { get; set; }
        public Nullable<int> ccompania { get; set; }
        public Nullable<int> cagenciaingreso { get; set; }
        public Nullable<int> csucursalingreso { get; set; }
        public Nullable<int> verreg { get; set; }
        public Nullable<System.DateTime> fdocumento { get; set; }
        public Nullable<System.DateTime> fcaducidad { get; set; }
        public string concepto { get; set; }
        public Nullable<int> tipodocumentoccatalogo { get; set; }
        public string tipodocumentocdetalle { get; set; }
        public Nullable<int> formapagoccatalogo { get; set; }
        public string formapagocdetalle { get; set; }
        public Nullable<int> porcentajeivaccatalogo { get; set; }
        public string porcentajeivacdetalle { get; set; }
        public Nullable<int> porcentajeiceccatalogo { get; set; }
        public string porcentajeicecdetalle { get; set; }
        public Nullable<int> estadoccatalogo { get; set; }
        public string estadocdetalle { get; set; }
        public Nullable<decimal> subtotalsinimpuestos { get; set; }
        public Nullable<decimal> montoice { get; set; }
        public Nullable<decimal> baseimponible { get; set; }
        public Nullable<decimal> montoiva { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconplantilla tconplantilla { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenagencia tgenagencia { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tperproveedor tperproveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tconfacturaparqueadero> tconfacturaparqueadero { get; set; }
    }
}
