//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconretencionfuente: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string cctaporpagar { get; set; }
        public string codigosri { get; set; }
        public int secuencia { get; set; }
        public Nullable<decimal> baseimpair { get; set; }
        public Nullable<decimal> valretair { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcuentaporpagar tconcuentaporpagar { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconretencionair tconretencionair { get; set; }
    }
}
