//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconflujocajahistorial: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cflujocajahistorial { get; set; }
        public string ccuenta { get; set; }
        public int fcontable { get; set; }
        public int fproceso { get; set; }
        public string descripcion { get; set; }
        public decimal valor { get; set; }
        public decimal saldocuenta { get; set; }
        public Nullable<int> tipoflujoccatalogo { get; set; }
        public string tipoflujocdetalle { get; set; }
        public Nullable<int> tipooperacionccatalogo { get; set; }
        public string tipooperacioncdetalle { get; set; }
        public Nullable<int> tipoplanccatalogo { get; set; }
        public string tipoplancdetalle { get; set; }
    }
}
