//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconconciliacionbancaria: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cconconciliacionbancaria { get; set; }
        public Nullable<long> cconciliacionbancariamayor { get; set; }
        public Nullable<long> cconconciliacionbancariaextracto { get; set; }
        public Nullable<long> conciliacionbancariaid { get; set; }
        public string cusuarioconcilia { get; set; }
        public Nullable<System.DateTime> fconcilia { get; set; }
        public bool automatico { get; set; }
        public string cestado { get; set; }
        public Nullable<int> secuencia { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconconciliacionestado tconconciliacionestado { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconconciliacionbancariaeb tconconciliacionbancariaeb { get; set; }
    }
}
