//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconplantilladetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int cplantilla { get; set; }
        public int ccompania { get; set; }
        public int secuencia { get; set; }
        public string cpartida { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<bool> debito { get; set; }
        public string ccuenta { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> centrocostosccatalogo { get; set; }
        public string centrocostoscdetalle { get; set; }
        public Nullable<int> campotablaccatalogo { get; set; }
        public string campotablacdetalle { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconplantilla tconplantilla { get; set; }
    }
}
