//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconnotacreditocompras: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int cnotacreditocompras { get; set; }
        public string ccomprobante { get; set; }
        public Nullable<int> fcontable { get; set; }
        public Nullable<int> particion { get; set; }
        public Nullable<int> ccompania { get; set; }
        public string cctaporpagar { get; set; }
        public Nullable<long> cpersona { get; set; }
        public string ccuentaafectacion { get; set; }
        public string numdocumento { get; set; }
        public Nullable<System.DateTime> fdocumento { get; set; }
        public string autorizacion { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> valoriva { get; set; }
        public Nullable<decimal> total { get; set; }
        public string numdocsustento { get; set; }
        public Nullable<System.DateTime> fdocsustento { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcomprobante tconcomprobante { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcuentaporpagar tconcuentaporpagar { get; set; }
    }
}
