//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tconcomprobantedetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string ccomprobante { get; set; }
        public int fcontable { get; set; }
        public int particion { get; set; }
        public int secuencia { get; set; }
        public int ccompania { get; set; }
        public Nullable<long> optlock { get; set; }
        public string ccompromiso { get; set; }
        public string cpartida { get; set; }
        public Nullable<int> cagencia { get; set; }
        public Nullable<int> csucursal { get; set; }
        public string ccuenta { get; set; }
        public Nullable<bool> debito { get; set; }
        public string cclase { get; set; }
        public string cmoneda { get; set; }
        public string cusuario { get; set; }
        public string cmonedaoficial { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> montooficial { get; set; }
        public Nullable<bool> suma { get; set; }
        public string numerodocumentobancario { get; set; }
        public Nullable<int> centrocostosccatalogo { get; set; }
        public string centrocostoscdetalle { get; set; }
        public Nullable<long> conciliacionbancariaid { get; set; }
        public bool ajustemayor { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcatalogo tconcatalogo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcomprobante tconcomprobante { get; set; }
    }
}
