//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tgenfechacontable: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int ccompania { get; set; }
        public int fcontable { get; set; }
        public Nullable<int> ftrabajo { get; set; }
        public Nullable<int> fanterior { get; set; }
        public Nullable<int> fproxima { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencompania tgencompania { get; set; }
    }
}
