//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tinvinversionrentavariable: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tinvinversionrentavariable()
        {
        }
    
        public long cinversionrentavariable { get; set; }
        public Nullable<long> cinversion { get; set; }
        public Nullable<decimal> pagoefectivo { get; set; }
        public Nullable<int> bancoccatalogo { get; set; }
        public string bancocdetalle { get; set; }
        public string numerocheque { get; set; }
        public Nullable<decimal> pagoaccionespreciounitario { get; set; }
        public Nullable<decimal> pagoaccionesnumeroacciones { get; set; }
        public Nullable<decimal> pagoaccionesmontototal { get; set; }
        public Nullable<int> estadoccatalogo { get; set; }
        public string estadocdetalle { get; set; }
        public string comentariosingreso { get; set; }
        public string comentariosaprobacion { get; set; }
        public string comentariosdevolucion { get; set; }
        public string comentariosanulacion { get; set; }
        public string numerooficiopago { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tinvcontabilizacion> tinvcontabilizacion { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tinvinversion tinvinversion { get; set; }
    }
}
