//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tinvinversionhis: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tinvinversionhis()
        {
        }
    
        public long cinversionhis { get; set; }
        public Nullable<long> cinversion { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<int> fsistema { get; set; }
        public Nullable<decimal> tasaanterior { get; set; }
        public Nullable<decimal> tasanueva { get; set; }
        public Nullable<decimal> interesanterior { get; set; }
        public Nullable<decimal> interesnuevo { get; set; }
        public Nullable<decimal> interesdiferencia { get; set; }
        public Nullable<decimal> capitalanterior { get; set; }
        public Nullable<decimal> capitalnuevo { get; set; }
        public Nullable<decimal> capitaldiferencia { get; set; }
        public Nullable<decimal> tir { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tinvcontabilizacion> tinvcontabilizacion { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tinvinversion tinvinversion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tinvtablaamortizacionhis> tinvtablaamortizacionhis { get; set; }
    }
}
