//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tlotemodulo: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tlotemodulo()
        {
        }
    
        public string clote { get; set; }
        public int cmodulo { get; set; }
        public Nullable<long> cpersonaresponsable { get; set; }
        public Nullable<int> ccompania { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> numerohilos { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> cmodulodependencia { get; set; }
        public Nullable<bool> valprocesoantprev { get; set; }
        public Nullable<bool> valprocesoantregistros { get; set; }
        public Nullable<bool> valprocesoantfin { get; set; }
        public string modoejecucion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenmodulo tgenmodulo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tlotecodigo tlotecodigo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tlotemodulotareas> tlotemodulotareas { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tperpersona tperpersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tloteresultado> tloteresultado { get; set; }
    }
}
