//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tmonrubromapeoconcepto: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int ctransaccion { get; set; }
        public int cmodulo { get; set; }
        public int crubro { get; set; }
        public int cconcepto { get; set; }
        public Nullable<int> crubropantalla { get; set; }
        public Nullable<bool> calculavalores { get; set; }
        public Nullable<int> rubromontobase { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tmonconcepto tmonconcepto { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tmonrubro tmonrubro { get; set; }
    }
}
