//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tnomvacacion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cvacacion { get; set; }
        public Nullable<long> csolicitud { get; set; }
        public Nullable<long> remplazocfuncionario { get; set; }
        public Nullable<System.DateTime> finicio { get; set; }
        public Nullable<System.DateTime> ffin { get; set; }
        public Nullable<decimal> dias { get; set; }
        public Nullable<decimal> restantes { get; set; }
        public Nullable<bool> cambio { get; set; }
        public Nullable<long> cgesarchivo { get; set; }
        public string comentario { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tnomsolicitud tnomsolicitud { get; set; }
    }
}
