//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tnomjubilaciontotal: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long ctotal { get; set; }
        public long cjubilaciondetalle { get; set; }
        public Nullable<int> tipoccatalogo { get; set; }
        public string tipocdetalle { get; set; }
        public Nullable<long> cjubilacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> ingreso { get; set; }
        public Nullable<bool> porcentual { get; set; }
        public Nullable<decimal> calculado { get; set; }
        public Nullable<decimal> fingreso { get; set; }
        public Nullable<decimal> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tnomjubilacion tnomjubilacion { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tnomjubilaciondetalle tnomjubilaciondetalle { get; set; }
    }
}
