//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tnomdiatrabajado: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int cdiastrab { get; set; }
        public Nullable<long> cfuncionario { get; set; }
        public System.DateTime finicio { get; set; }
        public System.DateTime ffin { get; set; }
        public Nullable<int> ccatalogo { get; set; }
        public string cdetalle { get; set; }
        public bool estado { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> hinicio { get; set; }
        public Nullable<System.DateTime> hfin { get; set; }
        public bool completo { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario { get; set; }
    }
}
