//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tnomliquidacion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tnomliquidacion()
        {
        }
    
        public long cliquidacion { get; set; }
        public Nullable<long> ccontrato { get; set; }
        public Nullable<long> anio { get; set; }
        public Nullable<long> ccargo { get; set; }
        public Nullable<long> cfuncionario { get; set; }
        public Nullable<System.DateTime> fvinculacion { get; set; }
        public Nullable<System.DateTime> fdesvinculacion { get; set; }
        public Nullable<decimal> totalingresos { get; set; }
        public Nullable<decimal> totalegresos { get; set; }
        public Nullable<decimal> totaldiasvacaciones { get; set; }
        public Nullable<decimal> aniostrabajadosexacto { get; set; }
        public Nullable<decimal> aniostrabajadoscumplidos { get; set; }
        public Nullable<decimal> aniostrabajadosaproximado { get; set; }
        public string motivosalida { get; set; }
        public Nullable<decimal> diastrabajadosultimomes { get; set; }
        public Nullable<decimal> ultimaremuneracion { get; set; }
        public Nullable<bool> cerrada { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuariomod { get; set; }
        public string ccomprobante { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthcontrato tthcontrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tnomliquidaciondetalle> tnomliquidaciondetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario { get; set; }
    }
}
