//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tnomimpuestorenta: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long anio { get; set; }
        public long cfuncionario { get; set; }
        public Nullable<decimal> totingresoempresa { get; set; }
        public Nullable<decimal> totingresoexternos { get; set; }
        public Nullable<decimal> totingresos { get; set; }
        public Nullable<decimal> vvivienda { get; set; }
        public Nullable<decimal> veducacion { get; set; }
        public Nullable<decimal> vsalud { get; set; }
        public Nullable<decimal> vvestimenta { get; set; }
        public Nullable<decimal> valimentacion { get; set; }
        public Nullable<decimal> vtotal { get; set; }
        public Nullable<bool> aprobado { get; set; }
        public Nullable<decimal> viess { get; set; }
        public Nullable<decimal> cpagado { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tnomparametro tnomparametro { get; set; }
    }
}
