//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tnomfondoreserva: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cfondoreserva { get; set; }
        public Nullable<int> mesccatalogo { get; set; }
        public string mescdetalle { get; set; }
        public Nullable<System.DateTime> fechageneracion { get; set; }
        public Nullable<long> cfuncionario { get; set; }
        public Nullable<long> anio { get; set; }
        public Nullable<bool> tienesolicitud { get; set; }
        public Nullable<System.DateTime> fechasolicitud { get; set; }
        public Nullable<bool> tienecargos { get; set; }
        public Nullable<bool> tienederecho { get; set; }
        public Nullable<bool> proporcional { get; set; }
        public Nullable<int> diasproporcionales { get; set; }
        public decimal sueldoactual { get; set; }
        public decimal factorfr { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> accionccatalogo { get; set; }
        public string accioncdetalle { get; set; }
        public Nullable<bool> mensualiza { get; set; }
        public Nullable<bool> contabilizado { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle1 { get; set; }
    }
}
