//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class todcauditoria: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cauditoria { get; set; }
        public Nullable<int> cestructura { get; set; }
        public string accion { get; set; }
        public string cusuario { get; set; }
        public Nullable<System.DateTime> fechahora { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual todcestructura todcestructura { get; set; }
    }
}
