//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tperproveedor: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tperproveedor()
        {
        }
    
        public long cpersona { get; set; }
        public int ccompania { get; set; }
        public string ccuenta { get; set; }
        public int verreg { get; set; }
        public Nullable<long> optlock { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string nombrecomercial { get; set; }
        public string email { get; set; }
        public Nullable<bool> cliente { get; set; }
        public Nullable<bool> contribuyentespecial { get; set; }
        public bool pagoporbce { get; set; }
        public string cactividad { get; set; }
        public string contacto { get; set; }
        public Nullable<long> contactocpersona { get; set; }
        public Nullable<int> contactoccompania { get; set; }
        public Nullable<int> tipoinstitucionccatalogo { get; set; }
        public string tipoinstitucioncdetalle { get; set; }
        public Nullable<int> estadoccatalogo { get; set; }
        public string estadoccdetalle { get; set; }
        public Nullable<int> tipoidentificacionccatalogo { get; set; }
        public string tipoidentificacioncdetalle { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tconcuentaporcobrar> tconcuentaporcobrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tconcuentaporpagar> tconcuentaporpagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tcongarantiaparqueadero> tcongarantiaparqueadero { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle1 { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle2 { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tperactividadeconomica tperactividadeconomica { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tperpersona tperpersona { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tperpersona tperpersona1 { get; set; }
    }
}
