//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpptcompromisodetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string ccompromiso { get; set; }
        public string cpartidagasto { get; set; }
        public int aniofiscal { get; set; }
        public Nullable<int> secuencia { get; set; }
        public decimal valor { get; set; }
        public Nullable<decimal> valorpagado { get; set; }
        public string infoadicional { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string ccertificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpptcompromiso tpptcompromiso { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpptpartidagasto tpptpartidagasto { get; set; }
    }
}
