//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tppthistorialpartidagasto: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long chpartidagasto { get; set; }
        public string cpartidagasto { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<int> aniofiscal { get; set; }
        public string ccompromiso { get; set; }
        public string cafectacion { get; set; }
        public string cliberacion { get; set; }
        public string creforma { get; set; }
        public string ccomprobante { get; set; }
        public string concepto { get; set; }
        public string infoadicional { get; set; }
        public decimal vtransaccion { get; set; }
        public Nullable<decimal> vasignacioninicial { get; set; }
        public Nullable<decimal> vmodificado { get; set; }
        public Nullable<decimal> vcodificado { get; set; }
        public Nullable<decimal> vcertificado { get; set; }
        public Nullable<decimal> vcompromiso { get; set; }
        public Nullable<decimal> vcomprometido { get; set; }
        public Nullable<decimal> vdevengado { get; set; }
        public Nullable<decimal> vpagado { get; set; }
        public Nullable<decimal> vsaldoporcomprometer { get; set; }
        public Nullable<decimal> vsaldopordevengar { get; set; }
        public Nullable<decimal> vsaldoporpagar { get; set; }
        public Nullable<decimal> porcenejecucion { get; set; }
        public Nullable<decimal> porcenparticipacion { get; set; }
        public string cusuarioing { get; set; }
    }
}
