//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpptpartidagasto: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tpptpartidagasto()
        {
        }
    
        public string cpartidagasto { get; set; }
        public Nullable<int> ccompania { get; set; }
        public string cclasificador { get; set; }
        public string padre { get; set; }
        public int aniofiscal { get; set; }
        public int nivel { get; set; }
        public bool movimiento { get; set; }
        public string nombre { get; set; }
        public bool activa { get; set; }
        public Nullable<decimal> vasignacioninicial { get; set; }
        public Nullable<decimal> vmodificado { get; set; }
        public Nullable<decimal> vcodificado { get; set; }
        public Nullable<decimal> vcertificado { get; set; }
        public Nullable<decimal> vcomprometido { get; set; }
        public Nullable<decimal> vdevengado { get; set; }
        public Nullable<decimal> vpagado { get; set; }
        public Nullable<decimal> vsaldoporcomprometer { get; set; }
        public Nullable<decimal> vsaldopordevengar { get; set; }
        public Nullable<decimal> vsaldoporpagar { get; set; }
        public Nullable<decimal> porcenejecucion { get; set; }
        public Nullable<decimal> porcenparticipacion { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public Nullable<int> fvigencia { get; set; }
        public decimal vsaldoporcertificar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tpptcertificaciondetalle> tpptcertificaciondetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpptclasificador tpptclasificador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tpptcompromisodetalle> tpptcompromisodetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tpptsaldoscierrepg> tpptsaldoscierrepg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tpptreformadetalle> tpptreformadetalle { get; set; }
    }
}
