//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpptcuentaclasificador: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string ccuenta { get; set; }
        public int ccompania { get; set; }
        public int cmodulo { get; set; }
        public string cclasificador { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tconcatalogo tconcatalogo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenmodulo tgenmodulo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpptclasificador tpptclasificador { get; set; }
    }
}
