//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpptreformadetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string creforma { get; set; }
        public int secuencia { get; set; }
        public string cpartidagasto { get; set; }
        public int aniofiscal { get; set; }
        public bool decremento { get; set; }
        public decimal valor { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpptpartidagasto tpptpartidagasto { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpptreforma tpptreforma { get; set; }
    }
}
