//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpreflujoexpediente: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long flujoid { get; set; }
        public long secuencia { get; set; }
        public int cetapaactual { get; set; }
        public Nullable<int> cetapasiguiente { get; set; }
        public Nullable<System.DateTime> fentrada { get; set; }
        public Nullable<System.DateTime> fsalida { get; set; }
        public Nullable<System.DateTime> fechamax { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> historico { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tpreexpediente tpreexpediente { get; set; }
    }
}
