//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpreexpedienteasignacion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string cexpediente { get; set; }
        public long cpersona { get; set; }
        public long secuencial { get; set; }
        public string csecuencia { get; set; }
        public System.DateTime fbaja { get; set; }
        public System.DateTime fingreso { get; set; }
        public bool estadoasignacion { get; set; }
        public string tipoexp { get; set; }
        public string cusuarioing { get; set; }
        public int cagencia { get; set; }
        public int csucursal { get; set; }
        public int ccompania { get; set; }
        public Nullable<int> ccatalogoestadoregistro { get; set; }
        public string cdetalleestadoregistro { get; set; }
        public Nullable<System.DateTime> fechamodificacionregistro { get; set; }
        public string cusuariomodificacionregistro { get; set; }
        public string comentarioregistro { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenagencia tgenagencia { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgensecuencia tgensecuencia { get; set; }
    }
}
