//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpreexpedienterequisitos: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long secuencia { get; set; }
        public int crequisito { get; set; }
        public Nullable<bool> opcional { get; set; }
        public string cusuarioverifica { get; set; }
        public Nullable<System.DateTime> freal { get; set; }
        public Nullable<bool> verificada { get; set; }
        public string comentario { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tprerequisitos tprerequisitos { get; set; }
    }
}
