//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tpredevaporte: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int cdevaporte { get; set; }
        public string ccomprobante { get; set; }
        public long cpersona { get; set; }
        public long cpersonabeneficiario { get; set; }
        public string numerooficio { get; set; }
        public string numeromemo { get; set; }
        public System.DateTime fdevaporte { get; set; }
        public decimal vaportepatronal { get; set; }
        public decimal vaportepersonal { get; set; }
        public bool eliminado { get; set; }
        public string comentario { get; set; }
        public System.DateTime fingreso { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public string cusuariomod { get; set; }
    }
}
