//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tsegusuariodetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public string cusuario { get; set; }
        public int ccompania { get; set; }
        public int verreg { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<int> veractual { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public Nullable<long> cpersona { get; set; }
        public Nullable<int> cagencia { get; set; }
        public Nullable<int> csucursal { get; set; }
        public Nullable<int> estatuscusuariocatalogo { get; set; }
        public string estatuscusuariocdetalle { get; set; }
        public string cidioma { get; set; }
        public string ccanal { get; set; }
        public Nullable<int> carea { get; set; }
        public string sobrenombre { get; set; }
        public string password { get; set; }
        public string agenciadelterminal { get; set; }
        public Nullable<bool> usuariobpm { get; set; }
        public string cambiopassword { get; set; }
        public string impresoraslip { get; set; }
        public string observacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenagencia tgenagencia { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenarea tgenarea { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencanales tgencanales { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenidioma tgenidioma { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tperpersona tperpersona { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsegusuario tsegusuario { get; set; }
    }
}
