//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tsgsaseguradora: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsgsaseguradora()
        {
        }
    
        public int caseguradora { get; set; }
        public Nullable<long> optlock { get; set; }
        public string ruc { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tipoinstitucionccatalogo { get; set; }
        public string tipoinstitucioncdetalle { get; set; }
        public Nullable<int> tipocuentaccatalogo { get; set; }
        public string tipocuentacdetalle { get; set; }
        public string numerocuentabancaria { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<long> cgesarchivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tsgspago> tsgspago { get; set; }
    }
}
