//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tsgspago: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tsgspago()
        {
        }
    
        public int cpago { get; set; }
        public Nullable<int> caseguradora { get; set; }
        public long numeroreferencia { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> freal { get; set; }
        public int fingreso { get; set; }
        public string mensaje { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsgsaseguradora tsgsaseguradora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tsgspoliza> tsgspoliza { get; set; }
    }
}
