//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tsgstiposegurorubros: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public int ctiposeguro { get; set; }
        public int secuencia { get; set; }
        public Nullable<long> optlock { get; set; }
        public string nombre { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<bool> esporcentaje { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<bool> esvalor { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<bool> activo { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsgstiposeguro tsgstiposeguro { get; set; }
    }
}
