//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tsoccesantiahistorico: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cpersona { get; set; }
        public int ccompania { get; set; }
        public int secuencia { get; set; }
        public int verreg { get; set; }
        public Nullable<long> optlock { get; set; }
        public Nullable<int> veractual { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
        public Nullable<int> cestadosocio { get; set; }
        public Nullable<long> csubestado { get; set; }
        public Nullable<System.DateTime> festado { get; set; }
        public string ordengen { get; set; }
        public Nullable<System.DateTime> fordengen { get; set; }
        public Nullable<long> cgradoactual { get; set; }
        public Nullable<long> cgradoproximo { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechaproceso { get; set; }
        public Nullable<bool> activo { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsocestadosocio tsocestadosocio { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsoctipobaja tsoctipobaja { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsoctipogrado tsoctipogrado { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tsoctipogrado tsoctipogrado1 { get; set; }
    }
}
