//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class ttesenvioarchivo: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long ctesenvioarchivo { get; set; }
        public Nullable<long> numeroreferencia { get; set; }
        public string observacion { get; set; }
        public string estado { get; set; }
        public Nullable<long> cantidadpago { get; set; }
        public Nullable<decimal> valorpago { get; set; }
        public string mespago { get; set; }
        public Nullable<int> control { get; set; }
        public Nullable<long> sumcontrol { get; set; }
        public int cempresa { get; set; }
        public string localidad { get; set; }
        public string cuentaorigen { get; set; }
        public string razonsocial { get; set; }
        public string cusuariorec { get; set; }
        public Nullable<System.DateTime> frecepcion { get; set; }
        public Nullable<bool> esproveedor { get; set; }
        public string tipotransaccion { get; set; }
        public string cusuarioing { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public string referenciabce { get; set; }
    }
}
