//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class ttesretroalimentacion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long cretroalimentacion { get; set; }
        public int cmoduloriginal { get; set; }
        public int ctransaccionoriginal { get; set; }
        public int cmodulodestino { get; set; }
        public int ctransacciondestino { get; set; }
        public bool activo { get; set; }
        public int orden { get; set; }
        public string descripcion { get; set; }
        public string tipomapeo { get; set; }
    }
}
