//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class ttesestadorespuesta: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long ctescrespuesta { get; set; }
        public string cestado { get; set; }
        public string codigorespuesta { get; set; }
        public string nombre { get; set; }
        public bool modificable { get; set; }
        public string tipotransaccion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ttescatalogoestado ttescatalogoestado { get; set; }
    }
}
