//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tthasignaciondetalle: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long casignaciondetalle { get; set; }
        public Nullable<long> casignacion { get; set; }
        public Nullable<long> ccalificacion { get; set; }
        public Nullable<long> cversion { get; set; }
        public decimal ccumplimiento { get; set; }
        public decimal ccalidadoportunidad { get; set; }
        public decimal ccconocimiento { get; set; }
        public decimal ccompetenciat { get; set; }
        public decimal ccompetenciac { get; set; }
        public decimal cusrinternos { get; set; }
        public decimal cusrexternos { get; set; }
        public decimal csanciones { get; set; }
        public decimal totalgeneral { get; set; }
        public Nullable<decimal> totalcumplimiento { get; set; }
        public Nullable<decimal> totalniveleseficiencia { get; set; }
        public Nullable<decimal> totalcumplimientonormas { get; set; }
        public Nullable<decimal> totalusrinternos { get; set; }
        public Nullable<decimal> totalusrexternos { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public System.DateTime fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthevaluacionversion tthevaluacionversion { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthasignacionresp tthasignacionresp { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthcalificacioncualitativa tthcalificacioncualitativa { get; set; }
    }
}
