//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tthidioma: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long secuencia { get; set; }
        public long cfuncionario { get; set; }
        public string cpais { get; set; }
        public string cidioma { get; set; }
        public Nullable<long> cinstitucion { get; set; }
        public string titulo { get; set; }
        public int habla { get; set; }
        public int lee { get; set; }
        public int escribe { get; set; }
        public System.DateTime fcertificado { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgenidioma tgenidioma { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthinstitucioneducativa tthinstitucioneducativa { get; set; }
    }
}
