//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tthinterna: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tthinterna()
        {
        }
    
        public long cinterna { get; set; }
        public Nullable<long> cmatrizdetalle { get; set; }
        public Nullable<long> cversion { get; set; }
        public Nullable<long> cinfoempresa { get; set; }
        public Nullable<long> cfuncionario { get; set; }
        public Nullable<decimal> promedio { get; set; }
        public Nullable<bool> finalizada { get; set; }
        public string comentario { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthevaluacionversion tthevaluacionversion { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tthinternadetalle> tthinternadetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthmatrizcorrelaciondetalle tthmatrizcorrelaciondetalle { get; set; }
    }
}
