//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tthrequisitorelacionlaboral: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tthrequisitorelacionlaboral()
        {
        }
    
        public long crequisitorelacionlaboral { get; set; }
        public Nullable<int> documentoccatalogo { get; set; }
        public string documentocdetalle { get; set; }
        public Nullable<long> ctiporelacionlaboral { get; set; }
        public Nullable<int> fase { get; set; }
        public Nullable<bool> obligatorio { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual ICollection<tthrequisitohabilitante> tthrequisitohabilitante { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthtiporelacionlaboral tthtiporelacionlaboral { get; set; }
    }
}
