//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo
{
    using System;using modelo.helper;using modelo.helper.cartera;using modelo.interfaces;using System.Linq; using Newtonsoft.Json;using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    public partial class tthsancion: AbstractDto,IBean
    {
    public virtual object Clone() {
    			return this.MemberwiseClone();
            }
        public long csancion { get; set; }
        public Nullable<long> cperiodo { get; set; }
        public Nullable<long> sancionadocfuncionario { get; set; }
        public Nullable<long> sancionadorcfuncionario { get; set; }
        public int tiposancionccatalogo { get; set; }
        public string tiposancioncdetalle { get; set; }
        public string detallesancion { get; set; }
        public System.DateTime fsancion { get; set; }
        public Nullable<int> tipoamonestacionccatalogo { get; set; }
        public string tipoamonestacioncdetalle { get; set; }
        public Nullable<bool> aplicadescuento { get; set; }
        public Nullable<decimal> valordescuento { get; set; }
        public string cusuarioing { get; set; }
        public string cusuariomod { get; set; }
        public Nullable<System.DateTime> fingreso { get; set; }
        public Nullable<System.DateTime> fmodificacion { get; set; }
    
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tgencatalogodetalle tgencatalogodetalle1 { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthevaluacionperiodo tthevaluacionperiodo { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario { get; set; }
    [JsonIgnore]
    [IgnoreDataMember]
        public virtual tthfuncionario tthfuncionario1 { get; set; }
    }
}
